# Generated by Django 4.1.7 on 2023-06-14 09:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_options_student_add_to_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='davomat',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 14, 14, 53, 29, 503027)),
        ),
        migrations.AlterField(
            model_name='student',
            name='added',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 14, 14, 53, 29, 501403)),
        ),
    ]
