# Generated by Django 4.1.7 on 2023-06-10 08:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter course name', max_length=100, verbose_name='Course name')),
                ('cost', models.CharField(help_text='Enter cost', max_length=600, verbose_name='Cost')),
            ],
            options={
                'verbose_name': ' Course ',
                'verbose_name_plural': ' Courses ',
                'db_table': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, help_text='Enter Teacher Phone Number', max_length=15, null=True, unique=True, verbose_name='Teacher Phone Number')),
                ('added', models.DateTimeField()),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachercourse', to='courses.course')),
            ],
            options={
                'verbose_name': ' Employees',
                'verbose_name_plural': ' Employees ',
                'db_table': 'Employee',
            },
        ),
        migrations.CreateModel(
            name='EmpType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': ' EmpTypes ',
                'verbose_name_plural': ' EmpTypes ',
                'db_table': 'EmpType',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Room name')),
            ],
            options={
                'verbose_name': ' Room ',
                'verbose_name_plural': ' Rooms ',
                'db_table': 'Rooms',
            },
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Group name')),
                ('education', models.CharField(blank=True, choices=[('online', 'Online'), ('offline', 'Offline')], max_length=10, null=True)),
                ('day', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Mon', 'Mon'), ('Tue', 'Tue'), ('Wed', 'Wed'), ('Thu', 'Thu'), ('Fri', 'Fri'), ('Sat', 'Sat'), ('Sun', 'Sun')], max_length=100, null=True)),
                ('status', models.CharField(blank=True, choices=[('active', 'Active'), ('waiting', 'Waiting')], max_length=10, null=True)),
                ('start', models.DateField(blank=True, null=True)),
                ('finish', models.DateField(blank=True, null=True)),
                ('start_lesson', models.TimeField(blank=True, null=True)),
                ('finish_lesson', models.TimeField(blank=True, null=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='courses.course')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='courses.room')),
                ('student', models.ManyToManyField(related_name='groups', to='students.student')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher', to='courses.employee')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groupuser', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': ' Group ',
                'verbose_name_plural': ' Groups ',
                'db_table': 'Groups',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles', to='courses.emptype'),
        ),
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('student', models.ManyToManyField(related_name='classes', to='students.student')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classuser', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': ' Class Room ',
                'verbose_name_plural': ' Class Room ',
                'db_table': 'Class Room',
            },
        ),
    ]
