# Generated by Django 4.1.7 on 2023-06-14 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classroom',
            options={'verbose_name_plural': ' Classrooms'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Employees'},
        ),
        migrations.AlterModelOptions(
            name='groups',
            options={'verbose_name': 'Group', 'verbose_name_plural': 'Groups'},
        ),
        migrations.AlterField(
            model_name='course',
            name='cost',
            field=models.CharField(blank=True, help_text='Enter cost', max_length=600, null=True, verbose_name='Cost'),
        ),
        migrations.RemoveField(
            model_name='employee',
            name='course',
        ),
        migrations.RemoveField(
            model_name='groups',
            name='course',
        ),
        migrations.RemoveField(
            model_name='groups',
            name='room',
        ),
        migrations.RemoveField(
            model_name='groups',
            name='teacher',
        ),
        migrations.AlterModelTable(
            name='groups',
            table='Grouppa',
        ),
        migrations.AddField(
            model_name='employee',
            name='course',
            field=models.ManyToManyField(to='courses.course'),
        ),
        migrations.AddField(
            model_name='groups',
            name='course',
            field=models.ManyToManyField(related_name='groups', to='courses.course'),
        ),
        migrations.AddField(
            model_name='groups',
            name='room',
            field=models.ManyToManyField(related_name='groups_rooms', to='courses.room'),
        ),
        migrations.AddField(
            model_name='groups',
            name='teacher',
            field=models.ManyToManyField(related_name='teacher', to='courses.employee'),
        ),
    ]
