# Generated by Django 4.1.7 on 2023-06-14 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_classroom_options_alter_course_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groups',
            name='student',
        ),
    ]
